sudo: required

language: ruby

services:
  - docker

script:
  - docker build -t chakkritte/docker-nginx docker-nginx/
  - docker run -d -p 80:81 chakkritte/docker-nginx
  
  - docker build -t chakkritte/docker-caffe docker-caffe/
  - docker run -d -p 80:82 chakkritte/docker-caffe
  
  - docker build -t chakkritte/docker-nginx-hhvm docker-nginx-hhvm/
  - docker run -d -p 80:83 chakkritte/docker-nginx-hhvm
  
  - docker build -t chakkritte/docker-speech-recognition docker-speech-recognition/
  - docker run -d -p 80:84 chakkritte/docker-speech-recognition
  
  - docker ps -a
